apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: carlosfonsecam/nginx-openshift:v1
        ports:
        - containerPort: 8080
        volumenMonts:
        - name: tmp 
          mountPath: /tmp
      volumes:
      - name: tmp
        emptyDir: {}